# Generated by Django 3.2.14 on 2025-07-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250715_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Non-IT', 'Non-IT')], max_length=50, null=True),
        ),
    ]
