# Generated by Django 3.2.14 on 2025-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('transcript', models.TextField()),
                ('fluency', models.IntegerField()),
                ('vocabulary', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('summary', models.TextField()),
                ('suggestions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
