# Generated by Django 3.2.14 on 2025-07-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testsystem', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='tabswitchlog',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.testsession'),
        ),
        migrations.AddField(
            model_name='tabswitchlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='cameralog',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.testsession'),
        ),
        migrations.AddField(
            model_name='cameralog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
