# Generated by Django 3.2.14 on 2025-07-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
